In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
import warnings

ModuleNotFoundError: No module named 'seaborn'

In [169]:
Data = pd.read_csv("diabetes.csv")
Data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [170]:
df = pd.DataFrame(Data.drop('Pregnancies', axis=1))
df

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        148             72             35        0  33.6   
1         85             66             29        0  26.6   
2        183             64              0        0  23.3   
3         89             66             23       94  28.1   
4        137             40             35      168  43.1   
..       ...            ...            ...      ...   ...   
763      101             76             48      180  32.9   
764      122             70             27        0  36.8   
765      121             72             23      112  26.2   
766      126             60              0        0  30.1   
767       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 8 columns]

In [171]:
DF.describe()

Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   120.894531      69.105469      20.536458   79.799479   31.992578   
std     31.972618      19.355807      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    140.250000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.240885    0.348958  
std                    0.331329   11.760232    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [172]:
DF.isnull().sum()

Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [173]:
X =pd.DataFrame(df,columns=['Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'])
Y = df['Outcome'].values.reshape(-1 , 1)

In [196]:
X_train ,X_test ,Y_train , Y_test = train_test_split(X,Y,  test_size=0.35 , random_state=0)

In [197]:
Model=GaussianNB()
Model.fit(X_train ,Y_train.ravel())
Y_pred = Model.predict(X_test)

In [198]:
print("Accuracy :",metrics.accuracy_score(Y_test , Y_pred))

Accuracy : 0.786046511627907


In [199]:
from sklearn.metrics import classification_report , confusion_matrix
Model.classes_

array([0, 1], dtype=int64)

In [200]:
confusion_matrix(Y , Model.predict(X))

array([[355,  55],
       [ 87, 117]], dtype=int64)

In [201]:
print(classification_report(Y , Model.predict(X)))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83       410
           1       0.68      0.57      0.62       204

    accuracy                           0.77       614
   macro avg       0.74      0.72      0.73       614
weighted avg       0.76      0.77      0.76       614



In [202]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [217]:
k_fold=KFold(5)
print(cross_val_score(Model, X,Y.ravel(),cv=k_fold , n_jobs=1))

[0.77235772 0.7398374  0.73170732 0.79674797 0.73770492]


In [204]:
df2 = df[df.index<153]
df3 = df[df.index>306]
df4 = pd.concat([df2,df3])
df4.reset_index(drop = True, inplace=True)
df4

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0        148             72             35        0  33.6   
1         85             66             29        0  26.6   
2        183             64              0        0  23.3   
3         89             66             23       94  28.1   
4        137             40             35      168  43.1   
..       ...            ...            ...      ...   ...   
609      101             76             48      180  32.9   
610      122             70             27        0  36.8   
611      121             72             23      112  26.2   
612      126             60              0        0  30.1   
613       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
609                     0.171   63        0  
610                     0.340   27        0  
611                     0.245   30        0  
612                     0.349   47        1  
613                     0.315   23        0  

[614 rows x 8 columns]

In [213]:
X=pd.DataFrame(df4 ,columns=['Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'])
Y=df4.Outcome.values.reshape(-1,1)

In [214]:
X_train , X_test , Y_train , Y_test =train_test_split(X,Y , test_size=0.35 , random_state=0)

In [207]:
model=GaussianNB(priors=None ,var_smoothing=1e-09)
model.fit(X_train ,Y_train.ravel())
y_pred=model.predict(X_test)

In [208]:
print('accuracy:',metrics.accuracy_score(Y_test,y_pred))

accuracy: 0.786046511627907


In [222]:
cor = np.corrcoef(df4.Age,df4.Insulin)
cor

array([[ 1.        , -0.05781713],
       [-0.05781713,  1.        ]])

In [209]:
confusion_matrix(Y , Model.predict(X))

array([[355,  55],
       [ 87, 117]], dtype=int64)

In [210]:
print(classification_report(Y, Model.predict(X)))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83       410
           1       0.68      0.57      0.62       204

    accuracy                           0.77       614
   macro avg       0.74      0.72      0.73       614
weighted avg       0.76      0.77      0.76       614



In [224]:
new_data = pd.DataFrame([[20, 25, 65, 41, 30, 35, 41]], columns=['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'])  
p1 = model.predict(new_data)  
print(p1)  

[1]
